In [2]:
# solve ax = b
import numpy as np
import random, math
import copy

a = random.randint(1, 3)
x = random.randint(5, 8)  # HW: random.randint(0, 7)
b = a*x
print('ax = b')
print('a is',a)
print('b is',b)

# Assumtion: we don't know 'x'
# Goal: find x for the given equation 'ax = b'

ax = b
a is 1
b is 5


In [85]:
q1 = a*a + 10*a*a - 2*a*b
q2 = 4*a*a + 20*a*a - 4*a*b
q1q2 = 4*a*a
print('q1 is',q1)
print('q2 is',q2)
print('q1q2 is',q1q2)

LE = -(25*a*a+b*b-10*a*b)
print('The lowest energy is',LE)

q1 is -588
q2 is -1168
q1q2 is 16
The lowest energy is -21904


In [87]:
from dwave.system import DWaveSampler, EmbeddingComposite
sampler_auto = EmbeddingComposite(DWaveSampler(solver={'qpu': True}))

linear = {('q1','q1'):-588, ('q2','q2'):-1168}
quadratic = {('q1','q2'):16}

Q = dict(linear)
Q.update(quadratic)

sampleset = sampler_auto.sample_qubo(Q, num_reads=100)
print(sampleset)

  q1 q2  energy num_oc. chain_.
0  1  1 -1740.0     100     0.0
['BINARY', 1 rows, 100 samples, 2 variables]


In [6]:
sol_x = 5 + 1*0 + 2*0  #5 + 1*q1 + 2*q2


In [7]:
sol_x

5

In [ ]:
# HW1. -10 <= x <= -7  :  random.randint(-10, -7)
# HW2. 7 <= x <= 14    :  random.randint(7, 14)
# Hint: think the size of range x first

In [10]:
# HW 2
# solve ax = b
import numpy as np
import random, math
import copy

a = random.randint(1, 3)
x = random.randint(7, 14)  # HW: random.randint(7, 14)
b = a*x
print('ax = b')
print('a is',a)
print('b is',b)

# Assumtion: we don't know 'x'
# Goal: find x for the given equation 'ax = b'

ax = b
a is 3
b is 33


In [21]:
q1 = a*a - 2*a*b + 14*a*a
q2 = 4*a*a - 4*a*b + 28*a*a
q3 = 16*a*a - 8*a*b + 56*a*a
q1q2 = 4*a*a
q1q3 = 8*a*a 
q2q3 = 16*a*a
print('q1 is',q1)
print('q2 is',q2)
print('q3 is',q3)
print('q1q2 is',q1q2)
print('q1q3 is',q1q3)
print('q2q3 is',q2q3)

LE = -(49*a*a + b*b - 14*a*b)
print('The lowest energy is',LE)

qubits = 3
QM = np.zeros((3,3))
QM[0][0] = q1
QM[1][1] = q2
QM[2][2] = q3
QM[0][1] = q1q2
QM[0][2] = q1q3
QM[1][2] = q2q3
print(QM)

# Print Python code for the run in D-Wave quantum processing unit
print("Running code for D-Wave:\n")
print("from dwave.system import DWaveSampler, EmbeddingComposite")
print("sampler_auto = EmbeddingComposite(DWaveSampler(solver={'qpu': True}))\n")
print("linear = {", end = "")
for i in range(qubits - 1): 
    linear = i + 1
    print ("('q",linear,"','q",linear,"'):",format(QM[i][i]),sep='', end = ", ")
print ("('q",qubits,"','q",qubits,"'):",format(QM[qubits-1][qubits-1]),"}", sep='')

print("\nquadratic = {", end = "")
for i in range(qubits-1):
    for j in range(i+1,qubits):
        if QM[i][j] != 0:
            qdrt1 = i + 1
            qdrt2 = j + 1
            if i == qubits-2 and j == qubits-1:
                print ("('q",qdrt1,"','q",qdrt2,"'):",format(QM[i][j]), "}", sep='')
            else:
                print ("('q",qdrt1,"','q",qdrt2,"'):",format(QM[i][j]), sep ='', end = ", ")

print("\nQ = dict(linear)")
print("Q.update(quadratic)\n")

qa_iter = 100
print("sampleset = sampler_auto.sample_qubo(Q, num_reads=",qa_iter,")", sep = "")
print("print(sampleset)") 

q1 is -63
q2 is -108
q3 is -144
q1q2 is 36
q1q3 is 72
q2q3 is 144
The lowest energy is -144
[[ -63.   36.   72.]
 [   0. -108.  144.]
 [   0.    0. -144.]]
Running code for D-Wave:

from dwave.system import DWaveSampler, EmbeddingComposite
sampler_auto = EmbeddingComposite(DWaveSampler(solver={'qpu': True}))

linear = {('q1','q1'):-63.0, ('q2','q2'):-108.0, ('q3','q3'):-144.0}

quadratic = {('q1','q2'):36.0, ('q1','q3'):72.0, ('q2','q3'):144.0}

Q = dict(linear)
Q.update(quadratic)

sampleset = sampler_auto.sample_qubo(Q, num_reads=1000)
print(sampleset)


In [22]:
from dwave.system import DWaveSampler, EmbeddingComposite
sampler_auto = EmbeddingComposite(DWaveSampler(solver={'qpu': True}))

linear = {('q1','q1'):-63.0, ('q2','q2'):-108.0, ('q3','q3'):-144.0}

quadratic = {('q1','q2'):36.0, ('q1','q3'):72.0, ('q2','q3'):144.0}

Q = dict(linear)
Q.update(quadratic)

sampleset = sampler_auto.sample_qubo(Q, num_reads=1000)
print(sampleset)

  q1 q2 q3 energy num_oc. chain_.
0  0  0  1 -144.0     787     0.0
1  1  0  1 -135.0      92     0.0
2  1  1  0 -135.0     119     0.0
3  0  1  0 -108.0       1     0.0
4  0  1  1 -108.0       1     0.0
['BINARY', 5 rows, 1000 samples, 3 variables]


In [26]:
answer = sampler_auto.sample_qubo(Q)
qb_sol = list(answer.first[0].values())
sol_x = 7 + 1*qb_sol[0] + 2*qb_sol[1] + 4*qb_sol[2] 
print(sol_x)

11


In [27]:
# HW 1
# solve ax = b
import numpy as np
import random, math
import copy

a = random.randint(1, 3)
x = random.randint(-10, -7)  # HW: random.randint(-10, -7)
b = a*x
print('ax = b')
print('a is',a)
print('b is',b)

# Assumtion: we don't know 'x'
# Goal: find x for the given equation 'ax = b'

ax = b
a is 1
b is -8


In [33]:
q1 = a*a - 20*a*a - 2*a*b
q2 = 4*a*a - 40*a*a - 4*a*b
q1q2 = 4*a*a
print('q1 is',q1)
print('q2 is',q2)
print('q1q2 is',q1q2)

tl_val = -10
c = b - tl_val*a
LE = -(c*c)
print('The lowest energy is',LE)

qubits = 2
QM = np.zeros((qubits,qubits))
QM[0][0] = q1
QM[1][1] = q2

QM[0][1] = q1q2
print(QM)

# Print Python code for the run in D-Wave quantum processing unit
print("Running code for D-Wave:\n")
print("from dwave.system import DWaveSampler, EmbeddingComposite")
print("sampler_auto = EmbeddingComposite(DWaveSampler(solver={'qpu': True}))\n")
print("linear = {", end = "")
for i in range(qubits - 1): 
    linear = i + 1
    print ("('q",linear,"','q",linear,"'):",format(QM[i][i]),sep='', end = ", ")
print ("('q",qubits,"','q",qubits,"'):",format(QM[qubits-1][qubits-1]),"}", sep='')

print("\nquadratic = {", end = "")
for i in range(qubits-1):
    for j in range(i+1,qubits):
        if QM[i][j] != 0:
            qdrt1 = i + 1
            qdrt2 = j + 1
            if i == qubits-2 and j == qubits-1:
                print ("('q",qdrt1,"','q",qdrt2,"'):",format(QM[i][j]), "}", sep='')
            else:
                print ("('q",qdrt1,"','q",qdrt2,"'):",format(QM[i][j]), sep ='', end = ", ")

print("\nQ = dict(linear)")
print("Q.update(quadratic)\n")

qa_iter = 100
print("sampleset = sampler_auto.sample_qubo(Q, num_reads=",qa_iter,")", sep = "")
print("print(sampleset)") 

q1 is -3
q2 is -4
q1q2 is 4
The lowest energy is -4
[[-3.  4.]
 [ 0. -4.]]
Running code for D-Wave:

from dwave.system import DWaveSampler, EmbeddingComposite
sampler_auto = EmbeddingComposite(DWaveSampler(solver={'qpu': True}))

linear = {('q1','q1'):-3.0, ('q2','q2'):-4.0}

quadratic = {('q1','q2'):4.0}

Q = dict(linear)
Q.update(quadratic)

sampleset = sampler_auto.sample_qubo(Q, num_reads=100)
print(sampleset)


In [32]:
from dwave.system import DWaveSampler, EmbeddingComposite
sampler_auto = EmbeddingComposite(DWaveSampler(solver={'qpu': True}))

linear = {('q1','q1'):-3.0, ('q2','q2'):-4.0}

quadratic = {('q1','q2'):4.0}

Q = dict(linear)
Q.update(quadratic)

sampleset = sampler_auto.sample_qubo(Q, num_reads=100)
print(sampleset)

  q1 q2 energy num_oc. chain_.
0  0  1   -4.0     100     0.0
['BINARY', 1 rows, 100 samples, 2 variables]


In [34]:
answer = sampler_auto.sample_qubo(Q)
qb_sol = list(answer.first[0].values())
sol_x = tl_val + 1*qb_sol[0] + 2*qb_sol[1] 
print(sol_x)

-8


In [ ]:
# HW1. -100 <= x <= -85  :  random.randint(-100, -85)
# HW2. 73 <= x <= 80     :  random.randint(73, 80)
# Hint: think the size of range x first

In [1]:
import numpy as np
import random, math
import copy

a = random.randint(1, 3)
x = random.randint(-100, -85)  # HW: random.randint(-100, -85)
b = a*x
print('ax = b')
print('a is',a)
print('b is',b)


ax = b
a is 1
b is -92


In [2]:
q1 = a*a - 200*a*a - 2*a*b
q2 = 4*a*a - 400*a*a - 4*a*b
q3 = 16*a*a - 800*a*a - 8*a*b
q4 = 64*a*a - 1600*a*a - 16*a*b
q1q2 = 4*a*a
q1q3 = 8*a*a
q1q4 = 16*a*a
q2q3 = 16*a*a
q2q4 = 32*a*a
q3q4 = 64*a*a
print('q1 is',q1)
print('q2 is',q2)
print('q3 is',q3)
print('q4 is',q4)
print('q1q2 is',q1q2)
print('q1q3 is',q1q3)
print('q1q4 is',q1q4)
print('q2q3 is',q2q3)
print('q2q4 is',q2q4)
print('q3q4 is',q3q4)

LE = -(10000*a*a + b*b + 200*a*b)
print('The lowest energy is',LE)

q1 is -15
q2 is -28
q3 is -48
q4 is -64
q1q2 is 4
q1q3 is 8
q1q4 is 16
q2q3 is 16
q2q4 is 32
q3q4 is 64
The lowest energy is -64


In [4]:
from dwave.system import DWaveSampler, EmbeddingComposite
sampler_auto = EmbeddingComposite(DWaveSampler(solver={'qpu': True}))

linear = {('q1','q1'):-15, ('q2','q2'):-28, ('q3','q3'):-48, ('q4','q4'):-64}
quadratic = {('q1','q2'):4,('q1','q3'):8,('q1','q4'):16,('q2','q3'):16,('q2','q4'):32,('q3','q4'):64}

Q = dict(linear)
Q.update(quadratic)

sampleset = sampler_auto.sample_qubo(Q, num_reads=100)
print(sampleset)

  q1 q2 q3 q4 energy num_oc. chain_.
0  0  0  0  1  -64.0      46     0.0
1  1  0  0  1  -63.0      21     0.0
2  1  1  1  0  -63.0      24     0.0
3  0  1  1  0  -60.0       3     0.0
4  0  1  0  1  -60.0       5     0.0
5  1  1  0  1  -55.0       1     0.0
['BINARY', 6 rows, 100 samples, 4 variables]


In [6]:
sol_x = 1*0 + 2*0 + 4*0 + 8*1 -100
print (sol_x)

-92


In [8]:
import numpy as np
import random, math
import copy

a = random.randint(1, 3)
x = random.randint(73, 80)  #random.randint(73, 80)
b = a*x
print('ax = b')
print('a is',a)
print('b is',b)

ax = b
a is 3
b is 219


In [10]:
q1 = a*a + 146*a*a - 2*a*b
q2 = 4*a*a + 292*a*a - 4*a*b
q3 = 16*a*a + 584*a*a - 8*a*b
q1q2 = 4*a*a
q1q3 = 8*a*a
q2q3 = 16*a*a
LE = -(5329*a*a + b*b - 146*a*b)
print('q1 is',q1)
print('q2 is',q2)
print('q3 is',q3)
print('q1q2 is',q1q2)
print('q1q3 is',q1q3)
print('q1q3 is',q2q3)
print('The lowest energy is',LE)

q1 is 9
q2 is 36
q3 is 144
q1q2 is 36
q1q3 is 72
q1q3 is 144
The lowest energy is 0


In [11]:
from dwave.system import DWaveSampler, EmbeddingComposite
sampler_auto = EmbeddingComposite(DWaveSampler(solver={'qpu': True}))

linear = {('q1','q1'):9, ('q2','q2'):36, ('q3','q3'):144}
quadratic = {('q1','q2'):36,('q1','q3'):72,('q2','q3'):144}

Q = dict(linear)
Q.update(quadratic)

sampleset = sampler_auto.sample_qubo(Q, num_reads=100)
print(sampleset)

  q1 q2 q3 energy num_oc. chain_.
0  0  0  0    0.0      78     0.0
1  1  0  0    9.0      22     0.0
['BINARY', 2 rows, 100 samples, 3 variables]


In [12]:
sol_x = 1*0 + 2*0 + 4*0 + 73
print (sol_x)

73
